version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: classroom-db
    environment:
      POSTGRES_DB: classroom
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "25432:5432"
    volumes:
      - pgdataclassroom:/var/lib/postgresql/data
    networks:
      - pgnet

volumes:
  pgdataclassroom:

networks:
  pgnet:

